{
  "hash": "8462ce1c5a8e5f02740994f3aaa8fdd7",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Result\"\nformat: html\n---\n\n\n\n::: {.cell}\n\n:::\n\n\n\n::: {.cell}\n\n:::\n\n\n\n\n::: {.cell}\n\n:::\n\n\n## Study Sample Characteristics\n\nBridge inspection data from the Federal Highway Administration were analyzed for bridges located in Douglas County, which includes the city of Omaha. A total of 390 bridges were included in the analysis after excluding records with missing values in key structural or traffic variables.\n\n\n::: {#tbl-summary-stat .cell tbl-cap='Descriptive statistics for traffic volume and bridge age among analyzed Douglas County bridges'}\n::: {.cell-output-display}\n\n\n|Variable           | Min|Median |Mean   |Max     |\n|:------------------|---:|:------|:------|:-------|\n|Daily Traffic Mean |  25|15,750 |36,947 |182,320 |\n|Bridge Age (years) |   2|39     |41     |106     |\n\n\n:::\n:::\n\n\nAs shown in @tbl-summary-stat, Average Daily Traffic ranged from 25 to 182,320 vehicles per day, with a median of 15,750 and a mean of 36,947. This wide spread reflects the mix of major arterial crossings and minor local bridges in Douglas County\n\nBridge age ranged from 2 to 106 years, with a median of 39 years and a mean of 41.3 years. The relatively high mean age suggests that a substantial portion of the county's bridge inventory predates modern design standards and may face greater maintenance demands.\n\nThe mean deck, superstructure, and substructure ratings were 6.73, 7.02, and 6.95, respectively, all falling within the \"fair\" range (5-6) on the 0-9 NBI scale, while the superstructure mean marginally exceeds the good threshold ($\\geq$ 7), indicating the overall structural inventory is in fair-to good condition.\n\n\n## Structural Condition  \n\nStructural conditions were evaluated using inspection ratings for bridge decks, superstructures, and substructures. These ratings range from 0 (failed condition) to 9 (excellent condition). Since these ratings are recorded as discrete integers rather than continuous measurements, they are best treated as ordered categorical variables; @fig-dist-deck-condition therefore displays counts as a bar chart rather than a histogram.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Distribution of Bridge Deck Condition Ratings in Douglas County, Nebraska.](result_files/figure-html/fig-dist-deck-condition-1.png){#fig-dist-deck-condition width=672}\n:::\n:::\n\nThe majority of bridges received deck condition ratings of 5, 6, or 7, consistent with the sample mean of 6.73. However, a meaningful minority of bridges fall at or below the rating-4 threshold. A Spearman correlation test confirmed a statistically significant negative relationship between bridge age and deck condition ($\\rho$ = -0.4, p = 0), indicating that older bridges tend to exhibit lower deck condition ratings — though the effect is modest, suggesting factors beyond age alone (e.g., maintenance history, traffic loading, construction materials) also play a role.\n\n## Traffic Exposure\n\nTraffic exposure was analyzed to evaluate the potential *consequences* of bridge failure. A structurally compromised bridge that carries tens of thousands of vehicles per day poses a fundamentally different public risk than one serving a low-volume rural road.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Distribution of Average Daily Traffic (ADT) for bridges in Douglas County, plotted on a logarithmic scale to accommodate the wide range of values. Most bridges carry between 1,000 and 100,000 vehicles per day.](result_files/figure-html/fig-adt-distribution-1.png){#fig-adt-distribution width=576}\n:::\n:::\n\n\nAs shown in @fig-adt-distribution, the distribution is left-skewed even on a log scale, with a small number of bridges supporting extremely high traffic volumes (exceeding 100,000 vehicles per day). These high-volume bridges represent critical nodes in Omaha's transportation network where a failure would have the most immediate regional impact.\n\nThe correlation between deck condition and traffic volume was weak and not statistically significant ($\\rho$ = 0.17, p = 0.001). This is an important finding: bridge condition does not appear to be better or worse on higher-traffic routes, which means high-traffic bridges are not receiving systematically stronger maintenance relative to their exposure.\n\n\n::: {.cell}\n\n:::\n\n\nOf the 390 bridges analyzed, 16 (4.1%) were classified as higher-risk based on having at least one structural condition rating at or below 4. The remaining 374 bridges were classified as lower risk.\n\nHigher-risk bridges were, on average, 29.7 years older than lower-risk bridges (mean age 69.8 vs. 40 years), reinforcing the age–condition relationship observed above. Their mean daily traffic (20,076 vehicles/day) was lower than that of lower-risk bridges (37,669 vehicles/day), though the difference should be interpreted cautiously given the high variability in ADT across both groups.\n\n## Traffic by Bridge Condition\n\nThe combined risk picture — structural condition against traffic load — is the central question for prioritizing interventions. @fig-condition-traffic displays the distribution of ADT by deck condition rating.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![Relationship between bridge structural condition and traffic exposure in Douglas County, Nebraska.](result_files/figure-html/fig-condition-traffic-1.png){#fig-condition-traffic width=672}\n:::\n:::\n\n\n@fig-condition-traffic reveals a finding that carries direct policy implications: several bridges rated at 4 or below carry daily traffic volumes in the tens of thousands. These bridges sit in the upper-left danger zone — structurally compromised yet heavily used — and represent the clearest candidates for prioritized inspection and intervention. At the same time, the wide interquartile ranges within each rating category confirm that condition rating alone is not a reliable proxy for traffic exposure; both dimensions must be considered together when allocating limited maintenance resources.\n\n\n",
    "supporting": [
      "result_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}